- name: my playbook
  hosts: localhost
  vars_files: #takes precedence over vars
    - Eloise.yaml
  vars:
    my_name: "Eloise"
    repo_url: https://gitlab.com/Reece-Elder/devops-m5-rds.git
    new_file: "/home/ubuntu/ansible/example.txt"
    append_text: "this is an example"
  vars_prompt: #takes precedence over all other vars
    - name: "package_name"
      prompt: "enter the package name to install"
      default: "unzip"
    - name: "append_text"
      prompt: "enter text to append to the file"
      private: no #using no allows you to see what you're typing in the prompt
  
  tasks:
    - name: print name
      debug:
        msg: "my name is {{ my_name }}"

        # cmd line: --extra-vars or -e "my_name=Eloise2"
    - name: clone repo
      git:
        repo: "{{ repo_url }}"
        dest: /home/ubuntu/ansible/cloned-repo

    - name: install package
      become: yes
      package:
        name: "{{ package_name }}"
        state: present

    - name: install nginx
      become: true
      package:
        name: nginx
        state: present
        update_cache: true
      notify: 
        - restart nginx
    
    - name: create new file
      file:
        path: "{{ new_file }}"
        state: touch

    - name: Append text
      lineinfile:
        path: "{{ new_file }}"
        line: "{{ append_text }}"
        state: present
        create: true

  handlers: #handlers at the end of the file, only run if a task notifies them.
    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
